#
# 手動リリース
#

name: manual_release

on:
  workflow_dispatch:

jobs:
  # GitHubリリース発行
  release_to_github:
    runs-on: ubuntu-latest

    steps:
      - name: Specify current version
        run: |
          CURRENT_VERSION=`cat setup.cfg | grep "^version=" | sed 's/version=//'`
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Publish release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true

  # PyPIリリース発行
  release_to_pypi:
    runs-on: ubuntu-latest

    steps:
      # masterブランチをチェックアウト
      - uses: actions/checkout@v3
        with:
          ref: "master"

      # Pythonセットアップ
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ライブラリのビルド
      - name: Install pypa/build
        run: python -m pip install build --user

      # アップロード準備
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      # PyPIへアップロード
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
