#
# Publish package to TestPyPI when pre-release is created
#

name: Publish to TestPyPI when pre-released

on:
  release:
    types:
      - prereleased

jobs:
  testpypi-publish:
    name: Upload release to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/tmcsh

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "master"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
